"""initial

Revision ID: 0001
Revises:
Create Date: 2026-08-26 20:27:25.065290
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_kind", sa.String(), nullable=False),
        sa.Column("target_key", sa.String(collation="NOCASE"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_kind", "target_key"),
    )
    with op.batch_alter_table("annotations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_annotations_target_key"), ["target_key"], unique=False)

    op.create_table(
        "meta",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connection_name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("phase", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("server_name", sa.String(), nullable=True),
        sa.Column("server_version", sa.String(), nullable=True),
        sa.Column("server_edition", sa.String(), nullable=True),
        sa.Column("server_start_time", sa.DateTime(), nullable=True),
        sa.Column("auth_scheme", sa.String(), nullable=True),
        sa.Column("driver", sa.String(), nullable=True),
        sa.Column("options_json", sa.Text(), nullable=True),
        sa.Column("config_json", sa.Text(), nullable=True),
        sa.Column("summary_json", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scans_connection_name"), ["connection_name"], unique=False
        )

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(collation="NOCASE"), nullable=False),
        sa.Column("color", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "databases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("database_id", sa.Integer(), nullable=True),
        sa.Column("collation", sa.String(), nullable=True),
        sa.Column("compatibility_level", sa.Integer(), nullable=True),
        sa.Column("is_configured", sa.Boolean(), nullable=False),
        sa.Column("selected_schemas_json", sa.Text(), nullable=True),
        sa.Column("has_view_definition", sa.Boolean(), nullable=True),
        sa.Column("has_view_database_state", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id", "name"),
    )
    with op.batch_alter_table("databases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_databases_scan_id"), ["scan_id"], unique=False)

    op.create_table(
        "scan_warnings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(), nullable=False),
        sa.Column("database_name", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scan_warnings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scan_warnings_scan_id"), ["scan_id"], unique=False)

    op.create_table(
        "tag_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("target_kind", sa.String(), nullable=False),
        sa.Column("target_key", sa.String(collation="NOCASE"), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag_id", "target_kind", "target_key"),
    )
    with op.batch_alter_table("tag_assignments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tag_assignments_tag_id"), ["tag_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tag_assignments_target_key"), ["target_key"], unique=False
        )

    op.create_table(
        "objects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("database_id", sa.Integer(), nullable=True),
        sa.Column("object_key", sa.String(collation="NOCASE"), nullable=False),
        sa.Column("database_name", sa.String(), nullable=True),
        sa.Column("schema_name", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("sql_object_id", sa.Integer(), nullable=True),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("parent_object_id", sa.Integer(), nullable=True),
        sa.Column("external_server", sa.String(), nullable=True),
        sa.Column("base_object_name", sa.String(), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.Column("modify_date", sa.DateTime(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("uses_ansi_nulls", sa.Boolean(), nullable=True),
        sa.Column("uses_quoted_identifier", sa.Boolean(), nullable=True),
        sa.Column("is_schema_bound", sa.Boolean(), nullable=True),
        sa.Column("is_instead_of_trigger", sa.Boolean(), nullable=True),
        sa.Column("trigger_events", sa.String(), nullable=True),
        sa.Column("is_disabled", sa.Boolean(), nullable=True),
        sa.Column("has_dynamic_sql", sa.Boolean(), nullable=False),
        sa.Column("lineage_status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["database_id"], ["databases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id", "object_key"),
    )
    with op.batch_alter_table("objects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_objects_database_id"), ["database_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_objects_object_key"), ["object_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_objects_scan_id"), ["scan_id"], unique=False)
        batch_op.create_index("ix_objects_scan_kind", ["scan_id", "kind"], unique=False)
        batch_op.create_index("ix_objects_scan_schema", ["scan_id", "schema_name"], unique=False)
        batch_op.create_index(
            "ix_objects_scan_sql_object_id", ["scan_id", "sql_object_id"], unique=False
        )

    op.create_table(
        "columns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("column_key", sa.String(collation="NOCASE"), nullable=False),
        sa.Column("column_id", sa.Integer(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("column_kind", sa.String(), nullable=False),
        sa.Column("resultset_index", sa.Integer(), nullable=True),
        sa.Column("type_name", sa.String(), nullable=True),
        sa.Column("type_display", sa.String(), nullable=True),
        sa.Column("system_type_name", sa.String(), nullable=True),
        sa.Column("type_schema", sa.String(), nullable=True),
        sa.Column("is_user_defined_type", sa.Boolean(), nullable=True),
        sa.Column("max_length", sa.Integer(), nullable=True),
        sa.Column("precision", sa.Integer(), nullable=True),
        sa.Column("scale", sa.Integer(), nullable=True),
        sa.Column("is_nullable", sa.Boolean(), nullable=True),
        sa.Column("is_identity", sa.Boolean(), nullable=True),
        sa.Column("identity_seed", sa.String(), nullable=True),
        sa.Column("identity_increment", sa.String(), nullable=True),
        sa.Column("is_computed", sa.Boolean(), nullable=True),
        sa.Column("computed_definition", sa.Text(), nullable=True),
        sa.Column("is_persisted", sa.Boolean(), nullable=True),
        sa.Column("default_name", sa.String(), nullable=True),
        sa.Column("default_definition", sa.Text(), nullable=True),
        sa.Column("collation_name", sa.String(), nullable=True),
        sa.Column("is_rowguidcol", sa.Boolean(), nullable=True),
        sa.Column("generated_always_type", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id", "column_key"),
    )
    with op.batch_alter_table("columns", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_columns_column_key"), ["column_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_columns_scan_id"), ["scan_id"], unique=False)
        batch_op.create_index("ix_columns_scan_object", ["scan_id", "object_id"], unique=False)

    op.create_table(
        "foreign_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_object_id", sa.Integer(), nullable=False),
        sa.Column("referenced_object_id", sa.Integer(), nullable=False),
        sa.Column("delete_action", sa.String(), nullable=True),
        sa.Column("update_action", sa.String(), nullable=True),
        sa.Column("is_disabled", sa.Boolean(), nullable=True),
        sa.Column("is_not_trusted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["parent_object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referenced_object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("foreign_keys", schema=None) as batch_op:
        batch_op.create_index("ix_fk_scan_parent", ["scan_id", "parent_object_id"], unique=False)
        batch_op.create_index(
            "ix_fk_scan_referenced", ["scan_id", "referenced_object_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_foreign_keys_scan_id"), ["scan_id"], unique=False)

    op.create_table(
        "indexes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("index_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type_code", sa.Integer(), nullable=True),
        sa.Column("type_desc", sa.String(), nullable=True),
        sa.Column("is_unique", sa.Boolean(), nullable=True),
        sa.Column("is_primary_key", sa.Boolean(), nullable=True),
        sa.Column("is_unique_constraint", sa.Boolean(), nullable=True),
        sa.Column("has_filter", sa.Boolean(), nullable=True),
        sa.Column("filter_definition", sa.Text(), nullable=True),
        sa.Column("fill_factor", sa.Integer(), nullable=True),
        sa.Column("is_disabled", sa.Boolean(), nullable=True),
        sa.Column("is_padded", sa.Boolean(), nullable=True),
        sa.Column("data_space_name", sa.String(), nullable=True),
        sa.Column("data_space_type", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("indexes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_indexes_scan_id"), ["scan_id"], unique=False)
        batch_op.create_index("ix_indexes_scan_object", ["scan_id", "object_id"], unique=False)

    op.create_table(
        "lineage_issues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("statement_index", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lineage_issues", schema=None) as batch_op:
        batch_op.create_index("ix_issues_scan_object", ["scan_id", "object_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lineage_issues_scan_id"), ["scan_id"], unique=False)

    op.create_table(
        "missing_indexes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("index_handle", sa.Integer(), nullable=True),
        sa.Column("equality_columns", sa.String(), nullable=True),
        sa.Column("inequality_columns", sa.String(), nullable=True),
        sa.Column("included_columns", sa.String(), nullable=True),
        sa.Column("unique_compiles", sa.Integer(), nullable=True),
        sa.Column("user_seeks", sa.Integer(), nullable=True),
        sa.Column("user_scans", sa.Integer(), nullable=True),
        sa.Column("last_user_seek", sa.DateTime(), nullable=True),
        sa.Column("avg_total_user_cost", sa.Float(), nullable=True),
        sa.Column("avg_user_impact", sa.Float(), nullable=True),
        sa.Column("improvement_measure", sa.Float(), nullable=True),
        sa.Column("suggested_ddl", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("missing_indexes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_missing_indexes_scan_id"), ["scan_id"], unique=False)
        batch_op.create_index("ix_missing_scan_object", ["scan_id", "object_id"], unique=False)

    op.create_table(
        "parameters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("parameter_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type_name", sa.String(), nullable=True),
        sa.Column("type_display", sa.String(), nullable=True),
        sa.Column("max_length", sa.Integer(), nullable=True),
        sa.Column("precision", sa.Integer(), nullable=True),
        sa.Column("scale", sa.Integer(), nullable=True),
        sa.Column("is_output", sa.Boolean(), nullable=True),
        sa.Column("has_default_value", sa.Boolean(), nullable=True),
        sa.Column("default_value", sa.String(), nullable=True),
        sa.Column("is_readonly", sa.Boolean(), nullable=True),
        sa.Column("is_table_type", sa.Boolean(), nullable=True),
        sa.Column("is_return_value", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("parameters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_parameters_scan_id"), ["scan_id"], unique=False)
        batch_op.create_index("ix_parameters_scan_object", ["scan_id", "object_id"], unique=False)

    op.create_table(
        "proc_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("execution_count", sa.Integer(), nullable=True),
        sa.Column("total_elapsed_us", sa.Integer(), nullable=True),
        sa.Column("avg_elapsed_us", sa.Integer(), nullable=True),
        sa.Column("min_elapsed_us", sa.Integer(), nullable=True),
        sa.Column("max_elapsed_us", sa.Integer(), nullable=True),
        sa.Column("total_cpu_us", sa.Integer(), nullable=True),
        sa.Column("total_logical_reads", sa.Integer(), nullable=True),
        sa.Column("last_execution_time", sa.DateTime(), nullable=True),
        sa.Column("cached_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id", "object_id"),
    )
    with op.batch_alter_table("proc_stats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_proc_stats_scan_id"), ["scan_id"], unique=False)

    op.create_table(
        "table_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("data_kb", sa.Integer(), nullable=True),
        sa.Column("index_kb", sa.Integer(), nullable=True),
        sa.Column("reserved_kb", sa.Integer(), nullable=True),
        sa.Column("partition_count", sa.Integer(), nullable=True),
        sa.Column("is_heap", sa.Boolean(), nullable=True),
        sa.Column("compression", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id", "object_id"),
    )
    with op.batch_alter_table("table_stats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_table_stats_scan_id"), ["scan_id"], unique=False)

    op.create_table(
        "check_constraints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("column_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("is_disabled", sa.Boolean(), nullable=True),
        sa.Column("is_not_trusted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["column_id"], ["columns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("check_constraints", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_check_constraints_scan_id"), ["scan_id"], unique=False)
        batch_op.create_index("ix_checks_scan_object", ["scan_id", "object_id"], unique=False)

    op.create_table(
        "column_lineage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("source_object_id", sa.Integer(), nullable=True),
        sa.Column("source_column_id", sa.Integer(), nullable=True),
        sa.Column("source_column_name", sa.String(), nullable=True),
        sa.Column("target_object_id", sa.Integer(), nullable=False),
        sa.Column("target_column_id", sa.Integer(), nullable=False),
        sa.Column("via_object_id", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.String(), nullable=False),
        sa.Column("transform", sa.String(), nullable=False),
        sa.Column("statement_index", sa.Integer(), nullable=True),
        sa.Column("statement_kind", sa.String(), nullable=True),
        sa.Column("expression_sql", sa.Text(), nullable=True),
        sa.Column("via", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_column_id"], ["columns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_column_id"], ["columns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["via_object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("column_lineage", schema=None) as batch_op:
        batch_op.create_index(
            "ix_col_lineage_scan_source", ["scan_id", "source_column_id"], unique=False
        )
        batch_op.create_index(
            "ix_col_lineage_scan_source_obj", ["scan_id", "source_object_id"], unique=False
        )
        batch_op.create_index(
            "ix_col_lineage_scan_target", ["scan_id", "target_column_id"], unique=False
        )
        batch_op.create_index(
            "ix_col_lineage_scan_target_obj", ["scan_id", "target_object_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_column_lineage_scan_id"), ["scan_id"], unique=False)

    op.create_table(
        "foreign_key_columns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("foreign_key_id", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("parent_column_id", sa.Integer(), nullable=True),
        sa.Column("parent_column_name", sa.String(), nullable=False),
        sa.Column("referenced_column_id", sa.Integer(), nullable=True),
        sa.Column("referenced_column_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["foreign_key_id"], ["foreign_keys.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_column_id"], ["columns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referenced_column_id"], ["columns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("foreign_key_columns", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_foreign_key_columns_foreign_key_id"), ["foreign_key_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_foreign_key_columns_scan_id"), ["scan_id"], unique=False
        )

    op.create_table(
        "index_columns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("index_id", sa.Integer(), nullable=False),
        sa.Column("column_id", sa.Integer(), nullable=True),
        sa.Column("column_name", sa.String(), nullable=False),
        sa.Column("key_ordinal", sa.Integer(), nullable=True),
        sa.Column("is_descending", sa.Boolean(), nullable=True),
        sa.Column("is_included", sa.Boolean(), nullable=True),
        sa.Column("partition_ordinal", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["column_id"], ["columns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["index_id"], ["indexes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("index_columns", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_index_columns_index_id"), ["index_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_index_columns_scan_id"), ["scan_id"], unique=False)

    op.create_table(
        "index_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("index_id", sa.Integer(), nullable=False),
        sa.Column("user_seeks", sa.Integer(), nullable=False),
        sa.Column("user_scans", sa.Integer(), nullable=False),
        sa.Column("user_lookups", sa.Integer(), nullable=False),
        sa.Column("user_updates", sa.Integer(), nullable=False),
        sa.Column("last_user_seek", sa.DateTime(), nullable=True),
        sa.Column("last_user_scan", sa.DateTime(), nullable=True),
        sa.Column("last_user_lookup", sa.DateTime(), nullable=True),
        sa.Column("last_user_update", sa.DateTime(), nullable=True),
        sa.Column("is_unused", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["index_id"], ["indexes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id", "index_id"),
    )
    with op.batch_alter_table("index_usage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_index_usage_scan_id"), ["scan_id"], unique=False)

    op.create_table(
        "object_dependencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("source_object_id", sa.Integer(), nullable=False),
        sa.Column("target_object_id", sa.Integer(), nullable=True),
        sa.Column("edge_kind", sa.String(), nullable=False),
        sa.Column("resolution", sa.String(), nullable=False),
        sa.Column("is_ambiguous", sa.Boolean(), nullable=False),
        sa.Column("is_caller_dependent", sa.Boolean(), nullable=False),
        sa.Column("is_schema_bound", sa.Boolean(), nullable=False),
        sa.Column("referencing_column_id", sa.Integer(), nullable=True),
        sa.Column("referenced_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["referencing_column_id"], ["columns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("object_dependencies", schema=None) as batch_op:
        batch_op.create_index("ix_deps_scan_source", ["scan_id", "source_object_id"], unique=False)
        batch_op.create_index("ix_deps_scan_target", ["scan_id", "target_object_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_object_dependencies_scan_id"), ["scan_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("object_dependencies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_object_dependencies_scan_id"))
        batch_op.drop_index("ix_deps_scan_target")
        batch_op.drop_index("ix_deps_scan_source")

    op.drop_table("object_dependencies")
    with op.batch_alter_table("index_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_index_usage_scan_id"))

    op.drop_table("index_usage")
    with op.batch_alter_table("index_columns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_index_columns_scan_id"))
        batch_op.drop_index(batch_op.f("ix_index_columns_index_id"))

    op.drop_table("index_columns")
    with op.batch_alter_table("foreign_key_columns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_foreign_key_columns_scan_id"))
        batch_op.drop_index(batch_op.f("ix_foreign_key_columns_foreign_key_id"))

    op.drop_table("foreign_key_columns")
    with op.batch_alter_table("column_lineage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_column_lineage_scan_id"))
        batch_op.drop_index("ix_col_lineage_scan_target_obj")
        batch_op.drop_index("ix_col_lineage_scan_target")
        batch_op.drop_index("ix_col_lineage_scan_source_obj")
        batch_op.drop_index("ix_col_lineage_scan_source")

    op.drop_table("column_lineage")
    with op.batch_alter_table("check_constraints", schema=None) as batch_op:
        batch_op.drop_index("ix_checks_scan_object")
        batch_op.drop_index(batch_op.f("ix_check_constraints_scan_id"))

    op.drop_table("check_constraints")
    with op.batch_alter_table("table_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_table_stats_scan_id"))

    op.drop_table("table_stats")
    with op.batch_alter_table("proc_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proc_stats_scan_id"))

    op.drop_table("proc_stats")
    with op.batch_alter_table("parameters", schema=None) as batch_op:
        batch_op.drop_index("ix_parameters_scan_object")
        batch_op.drop_index(batch_op.f("ix_parameters_scan_id"))

    op.drop_table("parameters")
    with op.batch_alter_table("missing_indexes", schema=None) as batch_op:
        batch_op.drop_index("ix_missing_scan_object")
        batch_op.drop_index(batch_op.f("ix_missing_indexes_scan_id"))

    op.drop_table("missing_indexes")
    with op.batch_alter_table("lineage_issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lineage_issues_scan_id"))
        batch_op.drop_index("ix_issues_scan_object")

    op.drop_table("lineage_issues")
    with op.batch_alter_table("indexes", schema=None) as batch_op:
        batch_op.drop_index("ix_indexes_scan_object")
        batch_op.drop_index(batch_op.f("ix_indexes_scan_id"))

    op.drop_table("indexes")
    with op.batch_alter_table("foreign_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_foreign_keys_scan_id"))
        batch_op.drop_index("ix_fk_scan_referenced")
        batch_op.drop_index("ix_fk_scan_parent")

    op.drop_table("foreign_keys")
    with op.batch_alter_table("columns", schema=None) as batch_op:
        batch_op.drop_index("ix_columns_scan_object")
        batch_op.drop_index(batch_op.f("ix_columns_scan_id"))
        batch_op.drop_index(batch_op.f("ix_columns_column_key"))

    op.drop_table("columns")
    with op.batch_alter_table("objects", schema=None) as batch_op:
        batch_op.drop_index("ix_objects_scan_sql_object_id")
        batch_op.drop_index("ix_objects_scan_schema")
        batch_op.drop_index("ix_objects_scan_kind")
        batch_op.drop_index(batch_op.f("ix_objects_scan_id"))
        batch_op.drop_index(batch_op.f("ix_objects_object_key"))
        batch_op.drop_index(batch_op.f("ix_objects_database_id"))

    op.drop_table("objects")
    with op.batch_alter_table("tag_assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tag_assignments_target_key"))
        batch_op.drop_index(batch_op.f("ix_tag_assignments_tag_id"))

    op.drop_table("tag_assignments")
    with op.batch_alter_table("scan_warnings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_warnings_scan_id"))

    op.drop_table("scan_warnings")
    with op.batch_alter_table("databases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_databases_scan_id"))

    op.drop_table("databases")
    op.drop_table("tags")
    with op.batch_alter_table("scans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scans_connection_name"))

    op.drop_table("scans")
    op.drop_table("meta")
    with op.batch_alter_table("annotations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_annotations_target_key"))

    op.drop_table("annotations")
    # ### end Alembic commands ###
