/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_api_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{name}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Connection */
        post: operations["test_connection_api_connections__name__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{name}/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scans */
        get: operations["list_scans_api_connections__name__scans_get"];
        put?: never;
        /** Start Scan */
        post: operations["start_scan_api_connections__name__scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan */
        get: operations["get_scan_api_scans__scan_id__get"];
        put?: never;
        post?: never;
        /** Delete Scan */
        delete: operations["delete_scan_api_scans__scan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Scan */
        post: operations["cancel_scan_api_scans__scan_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Summary */
        get: operations["scan_summary_api_scans__scan_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Objects */
        get: operations["list_objects_api_scans__scan_id__objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/objects/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup Object */
        get: operations["lookup_object_api_scans__scan_id__objects_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/objects/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Object */
        get: operations["get_object_api_scans__scan_id__objects__object_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/objects/{object_id}/definition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Definition */
        get: operations["get_definition_api_scans__scan_id__objects__object_id__definition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_scans__scan_id__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/lineage/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Object Graph */
        get: operations["object_graph_api_scans__scan_id__lineage_objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/lineage/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Column Graph */
        get: operations["column_graph_api_scans__scan_id__lineage_columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/lineage/objects/{object_id}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Object Columns */
        get: operations["object_columns_api_scans__scan_id__lineage_objects__object_id__columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/lineage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lineage Summary */
        get: operations["lineage_summary_api_scans__scan_id__lineage_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/lineage/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lineage Issues */
        get: operations["lineage_issues_api_scans__scan_id__lineage_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/stats/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tables */
        get: operations["tables_api_scans__scan_id__stats_tables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/stats/indexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indexes */
        get: operations["indexes_api_scans__scan_id__stats_indexes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/stats/procs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Procs */
        get: operations["procs_api_scans__scan_id__stats_procs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/stats/missing-indexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Missing Indexes */
        get: operations["missing_indexes_api_scans__scan_id__stats_missing_indexes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Annotations */
        get: operations["list_annotations_api_annotations_get"];
        /** Put Annotation */
        put: operations["put_annotation_api_annotations_put"];
        post?: never;
        /** Delete Annotation */
        delete: operations["delete_annotation_api_annotations_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Annotation */
        Annotation: {
            /**
             * Target Kind
             * @enum {string}
             */
            target_kind: "object" | "column";
            /** Target Key */
            target_key: string;
            /** Connection */
            connection?: string | null;
            /** Db */
            db?: string | null;
            /** Schema */
            schema?: string | null;
            /** Name */
            name?: string | null;
            /** Column */
            column?: string | null;
            /** Description */
            description?: string | null;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[];
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** AnnotationUpsert */
        AnnotationUpsert: {
            /** Connection */
            connection: string;
            /** Db */
            db: string;
            /** Schema */
            schema: string;
            /** Name */
            name: string;
            /** Column */
            column?: string | null;
            /** Description */
            description?: string | null;
            /** Notes */
            notes?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** CheckConstraint */
        CheckConstraint: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Column */
            column?: string | null;
            /** Definition */
            definition?: string | null;
            /** Is Disabled */
            is_disabled?: boolean | null;
            /** Is Not Trusted */
            is_not_trusted?: boolean | null;
        };
        /** Column */
        Column: {
            /** Id */
            id: number;
            /** Ordinal */
            ordinal: number;
            /** Name */
            name: string;
            /**
             * Column Kind
             * @enum {string}
             */
            column_kind: "column" | "resultset" | "return_value";
            /** Type Display */
            type_display?: string | null;
            /** Is Nullable */
            is_nullable?: boolean | null;
            /** Is Identity */
            is_identity?: boolean | null;
            /** Is Computed */
            is_computed?: boolean | null;
            /** Computed Definition */
            computed_definition?: string | null;
            /** Default Definition */
            default_definition?: string | null;
            /** Collation */
            collation?: string | null;
            /**
             * In Primary Key
             * @default false
             */
            in_primary_key: boolean;
            fk_to?: components["schemas"]["FkTarget"] | null;
            /** Ms Description */
            ms_description?: string | null;
            /** Description */
            description?: string | null;
            lineage: components["schemas"]["ColumnLineageCounts"];
        };
        /** ColumnLineageCounts */
        ColumnLineageCounts: {
            /**
             * Upstream
             * @default 0
             */
            upstream: number;
            /**
             * Downstream
             * @default 0
             */
            downstream: number;
        };
        /** ColumnLineageEdge */
        ColumnLineageEdge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Source Column */
            source_column: string;
            /** Target */
            target: string;
            /** Target Column */
            target_column: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "exact" | "inferred" | "unresolved";
            /**
             * Transform
             * @enum {string}
             */
            transform: "passthrough" | "expression" | "aggregate" | "star" | "temp" | "pseudo" | "computed";
            /** Via Object Id */
            via_object_id?: number | null;
            /** Via Name */
            via_name?: string | null;
            /** Expression */
            expression?: string | null;
        };
        /** ColumnLineageFocus */
        ColumnLineageFocus: {
            /** Object Id */
            object_id: number;
            /** Column */
            column?: string | null;
        };
        /** ColumnLineageGraph */
        ColumnLineageGraph: {
            focus: components["schemas"]["ColumnLineageFocus"];
            /** Nodes */
            nodes: components["schemas"]["ColumnLineageNode"][];
            /** Edges */
            edges: components["schemas"]["ColumnLineageEdge"][];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** ColumnLineageNode */
        ColumnLineageNode: {
            /** Id */
            id: string;
            /** Object Id */
            object_id: number;
            /** Db */
            db?: string | null;
            /** Schema */
            schema?: string | null;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "table" | "view" | "procedure" | "scalar_function" | "inline_tvf" | "table_function" | "clr_function" | "trigger" | "synonym" | "sequence" | "table_type" | "temp_table" | "external";
            /**
             * Scope
             * @enum {string}
             */
            scope: "in_scope" | "cascaded" | "external";
            /** Hop */
            hop: number;
            /**
             * Has Lineage Issues
             * @default false
             */
            has_lineage_issues: boolean;
            more: components["schemas"]["LineageMore"];
            /** Columns */
            columns?: components["schemas"]["ColumnLineageNodeColumn"][];
            /**
             * Column Count Total
             * @default 0
             */
            column_count_total: number;
        };
        /** ColumnLineageNodeColumn */
        ColumnLineageNodeColumn: {
            /** Column Id */
            column_id: number;
            /** Name */
            name: string;
            /** Data Type */
            data_type?: string | null;
        };
        /** ConfidenceCounts */
        ConfidenceCounts: {
            /**
             * Exact
             * @default 0
             */
            exact: number;
            /**
             * Inferred
             * @default 0
             */
            inferred: number;
            /**
             * Unresolved
             * @default 0
             */
            unresolved: number;
        };
        /** ConfigOut */
        ConfigOut: {
            /** Config Path */
            config_path: string;
            /** Sqlite Path */
            sqlite_path: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
        };
        /** ConnectionDatabase */
        ConnectionDatabase: {
            /** Name */
            name: string;
            /** Schemas */
            schemas: string[];
        };
        /** ConnectionInfo */
        ConnectionInfo: {
            /** Name */
            name: string;
            /** Host */
            host: string;
            /** Port */
            port: number;
            /**
             * Auth Mode
             * @enum {string}
             */
            auth_mode: "sql" | "integrated";
            /** Username */
            username?: string | null;
            /**
             * Driver
             * @enum {string}
             */
            driver: "auto" | "pyodbc" | "pymssql";
            /** Databases */
            databases: components["schemas"]["ConnectionDatabase"][];
            latest_scan?: components["schemas"]["ScanSummary"] | null;
            /** Running Scan Id */
            running_scan_id?: number | null;
        };
        /** ConnectionTestDatabase */
        ConnectionTestDatabase: {
            /** Name */
            name: string;
            /** Reachable */
            reachable: boolean;
            /** Can View Definition */
            can_view_definition?: boolean | null;
            /** Can View Database State */
            can_view_database_state?: boolean | null;
            /** Error */
            error?: string | null;
        };
        /** ConnectionTestResult */
        ConnectionTestResult: {
            /** Ok */
            ok: boolean;
            /** Server Name */
            server_name?: string | null;
            /** Version */
            version?: string | null;
            /** Edition */
            edition?: string | null;
            /** Auth Scheme */
            auth_scheme?: string | null;
            /** Driver */
            driver?: ("pyodbc" | "pymssql") | null;
            /** Can View Server State */
            can_view_server_state?: boolean | null;
            /** Databases */
            databases?: components["schemas"]["ConnectionTestDatabase"][];
            /** Error */
            error?: string | null;
        };
        /** DatabaseOverview */
        DatabaseOverview: {
            /** Name */
            name: string;
            /** Is Configured */
            is_configured: boolean;
            /** Schemas */
            schemas: components["schemas"]["SchemaOverview"][];
        };
        /** Definition */
        Definition: {
            /** Definition */
            definition?: string | null;
            /**
             * Length
             * @default 0
             */
            length: number;
            /**
             * Has Dynamic Sql
             * @default false
             */
            has_dynamic_sql: boolean;
        };
        /** DepRef */
        DepRef: {
            /** Object Id */
            object_id?: number | null;
            /** Db */
            db?: string | null;
            /** Schema */
            schema?: string | null;
            /** Name */
            name: string;
            /** Kind */
            kind?: ("table" | "view" | "procedure" | "scalar_function" | "inline_tvf" | "table_function" | "clr_function" | "trigger" | "synonym" | "sequence" | "table_type" | "temp_table" | "external") | null;
            /** Scope */
            scope?: ("in_scope" | "cascaded" | "external") | null;
            /** Edge Kind */
            edge_kind: string;
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "resolved" | "caller_dependent" | "ambiguous" | "external" | "unresolved";
            /** Referenced Name */
            referenced_name?: string | null;
        };
        /** Dependencies */
        Dependencies: {
            /** Uses */
            uses?: components["schemas"]["DepRef"][];
            /** Used By */
            used_by?: components["schemas"]["DepRef"][];
        };
        /** ExecStats */
        ExecStats: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "exec";
            /** Exec Count */
            exec_count?: number | null;
            /** Total Ms */
            total_ms?: number | null;
            /** Avg Ms */
            avg_ms?: number | null;
            /** Min Ms */
            min_ms?: number | null;
            /** Max Ms */
            max_ms?: number | null;
            /** Total Cpu Ms */
            total_cpu_ms?: number | null;
            /** Total Logical Reads */
            total_logical_reads?: number | null;
            /** Last Exec At */
            last_exec_at?: string | null;
            /** Cached Since */
            cached_since?: string | null;
            /** Since Server Start */
            since_server_start?: string | null;
        };
        /** FkTarget */
        FkTarget: {
            /** Object Id */
            object_id: number;
            /** Schema */
            schema?: string | null;
            /** Name */
            name: string;
            /** Column */
            column: string;
        };
        /** ForeignKeyColumnPair */
        ForeignKeyColumnPair: {
            /** Column */
            column: string;
            /** Referenced Column */
            referenced_column: string;
        };
        /** ForeignKeyRef */
        ForeignKeyRef: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            parent: components["schemas"]["ObjectRef"];
            referenced: components["schemas"]["ObjectRef"];
            /** Columns */
            columns?: components["schemas"]["ForeignKeyColumnPair"][];
            /** Delete Action */
            delete_action?: string | null;
            /** Update Action */
            update_action?: string | null;
            /** Is Disabled */
            is_disabled?: boolean | null;
            /** Is Not Trusted */
            is_not_trusted?: boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
            /** Db Path */
            db_path: string;
        };
        /** Index */
        Index: {
            /** Id */
            id: number;
            /** Name */
            name?: string | null;
            /** Type Desc */
            type_desc?: string | null;
            /** Is Unique */
            is_unique?: boolean | null;
            /** Is Primary Key */
            is_primary_key?: boolean | null;
            /** Is Unique Constraint */
            is_unique_constraint?: boolean | null;
            /** Key Columns */
            key_columns?: components["schemas"]["IndexKeyColumn"][];
            /** Included Columns */
            included_columns?: string[];
            /** Filter */
            filter?: string | null;
            /** Is Disabled */
            is_disabled?: boolean | null;
            usage?: components["schemas"]["IndexUsage"] | null;
            /**
             * Is Unused
             * @default false
             */
            is_unused: boolean;
            /** Description */
            description?: string | null;
        };
        /** IndexKeyColumn */
        IndexKeyColumn: {
            /** Name */
            name: string;
            /**
             * Desc
             * @default false
             */
            desc: boolean;
        };
        /** IndexStatsRow */
        IndexStatsRow: {
            object: components["schemas"]["ObjectSummary"];
            /** Index Id */
            index_id: number;
            /** Index Name */
            index_name?: string | null;
            /** Type Desc */
            type_desc?: string | null;
            /** Is Unique */
            is_unique?: boolean | null;
            /** Is Primary Key */
            is_primary_key?: boolean | null;
            /** Is Unique Constraint */
            is_unique_constraint?: boolean | null;
            /** Key Columns */
            key_columns?: string[];
            /** Included Columns */
            included_columns?: string[];
            /**
             * Seeks
             * @default 0
             */
            seeks: number;
            /**
             * Scans
             * @default 0
             */
            scans: number;
            /**
             * Lookups
             * @default 0
             */
            lookups: number;
            /**
             * Updates
             * @default 0
             */
            updates: number;
            /** Last Seek */
            last_seek?: string | null;
            /** Last Scan */
            last_scan?: string | null;
            /** Last Lookup */
            last_lookup?: string | null;
            /** Last Update */
            last_update?: string | null;
            /**
             * Is Unused
             * @default false
             */
            is_unused: boolean;
        };
        /** IndexUsage */
        IndexUsage: {
            /**
             * Seeks
             * @default 0
             */
            seeks: number;
            /**
             * Scans
             * @default 0
             */
            scans: number;
            /**
             * Lookups
             * @default 0
             */
            lookups: number;
            /**
             * Updates
             * @default 0
             */
            updates: number;
            /** Last Seek */
            last_seek?: string | null;
            /** Last Scan */
            last_scan?: string | null;
            /** Last Lookup */
            last_lookup?: string | null;
            /** Last Update */
            last_update?: string | null;
        };
        /** KeyConstraint */
        KeyConstraint: {
            /** Name */
            name?: string | null;
            /** Type Desc */
            type_desc?: string | null;
            /** Columns */
            columns?: string[];
        };
        /** LineageCounts */
        LineageCounts: {
            /**
             * Upstream
             * @default 0
             */
            upstream: number;
            /**
             * Downstream
             * @default 0
             */
            downstream: number;
            /**
             * Columns With Lineage
             * @default 0
             */
            columns_with_lineage: number;
        };
        /** LineageEdge */
        LineageEdge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "catalog" | "fk" | "trigger" | "synonym" | "parsed_read" | "parsed_write" | "parsed_exec";
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "resolved" | "caller_dependent" | "ambiguous" | "external" | "unresolved";
            /** Detail */
            detail?: string | null;
        };
        /** LineageGraph */
        LineageGraph: {
            /** Focus */
            focus: string;
            /** Nodes */
            nodes: components["schemas"]["LineageNode"][];
            /** Edges */
            edges: components["schemas"]["LineageEdge"][];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** LineageHub */
        LineageHub: {
            /** Object Id */
            object_id: number;
            /** Db */
            db?: string | null;
            /** Schema */
            schema?: string | null;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Upstream */
            upstream: number;
            /** Downstream */
            downstream: number;
            /** Degree */
            degree: number;
        };
        /** LineageIssue */
        LineageIssue: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "parse_error" | "qualify_failed" | "lineage_failed" | "dynamic_sql" | "unsupported" | "column_count_mismatch" | "skipped" | "timeout" | "unresolved_ref";
            /** Statement Index */
            statement_index?: number | null;
            /** Message */
            message: string;
            /** Snippet */
            snippet?: string | null;
        };
        /** LineageIssueItem */
        LineageIssueItem: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "parse_error" | "qualify_failed" | "lineage_failed" | "dynamic_sql" | "unsupported" | "column_count_mismatch" | "skipped" | "timeout" | "unresolved_ref";
            /** Statement Index */
            statement_index?: number | null;
            /** Message */
            message: string;
            /** Snippet */
            snippet?: string | null;
            /** Id */
            id: number;
            object: components["schemas"]["ObjectRef"];
        };
        /** LineageMore */
        LineageMore: {
            /**
             * Upstream
             * @default 0
             */
            upstream: number;
            /**
             * Downstream
             * @default 0
             */
            downstream: number;
        };
        /** LineageNode */
        LineageNode: {
            /** Id */
            id: string;
            /** Object Id */
            object_id: number;
            /** Db */
            db?: string | null;
            /** Schema */
            schema?: string | null;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "table" | "view" | "procedure" | "scalar_function" | "inline_tvf" | "table_function" | "clr_function" | "trigger" | "synonym" | "sequence" | "table_type" | "temp_table" | "external";
            /**
             * Scope
             * @enum {string}
             */
            scope: "in_scope" | "cascaded" | "external";
            /** Hop */
            hop: number;
            /** Row Count */
            row_count?: number | null;
            /** Exec Count */
            exec_count?: number | null;
            /**
             * Has Lineage Issues
             * @default false
             */
            has_lineage_issues: boolean;
            more: components["schemas"]["LineageMore"];
        };
        /** LineageSummary */
        LineageSummary: {
            /** Objects */
            objects: number;
            /** Edges By Kind */
            edges_by_kind: {
                [key: string]: number;
            };
            /** Column Edges By Confidence */
            column_edges_by_confidence: {
                [key: string]: number;
            };
            /** Lineage Coverage */
            lineage_coverage?: number | null;
            /**
             * Objects With Issues
             * @default 0
             */
            objects_with_issues: number;
            /** Top Hubs */
            top_hubs?: components["schemas"]["LineageHub"][];
        };
        /** ListEnvelope[Annotation] */
        ListEnvelope_Annotation_: {
            /** Items */
            items: components["schemas"]["Annotation"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ListEnvelope[ConnectionInfo] */
        ListEnvelope_ConnectionInfo_: {
            /** Items */
            items: components["schemas"]["ConnectionInfo"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ListEnvelope[IndexStatsRow] */
        ListEnvelope_IndexStatsRow_: {
            /** Items */
            items: components["schemas"]["IndexStatsRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ListEnvelope[LineageIssueItem] */
        ListEnvelope_LineageIssueItem_: {
            /** Items */
            items: components["schemas"]["LineageIssueItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ListEnvelope[MissingIndexRow] */
        ListEnvelope_MissingIndexRow_: {
            /** Items */
            items: components["schemas"]["MissingIndexRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ListEnvelope[ObjectSummary] */
        ListEnvelope_ObjectSummary_: {
            /** Items */
            items: components["schemas"]["ObjectSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ListEnvelope[ProcStatsRow] */
        ListEnvelope_ProcStatsRow_: {
            /** Items */
            items: components["schemas"]["ProcStatsRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ListEnvelope[ScanSummary] */
        ListEnvelope_ScanSummary_: {
            /** Items */
            items: components["schemas"]["ScanSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ListEnvelope[TableStatsRow] */
        ListEnvelope_TableStatsRow_: {
            /** Items */
            items: components["schemas"]["TableStatsRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** MissingIndex */
        MissingIndex: {
            /** Id */
            id: number;
            /** Equality Columns */
            equality_columns?: string | null;
            /** Inequality Columns */
            inequality_columns?: string | null;
            /** Included Columns */
            included_columns?: string | null;
            /** User Seeks */
            user_seeks?: number | null;
            /** User Scans */
            user_scans?: number | null;
            /** Last User Seek */
            last_user_seek?: string | null;
            /** Avg Cost */
            avg_cost?: number | null;
            /** Avg Impact */
            avg_impact?: number | null;
            /** Improvement Measure */
            improvement_measure?: number | null;
            /** Suggested Ddl */
            suggested_ddl?: string | null;
        };
        /** MissingIndexRow */
        MissingIndexRow: {
            /** Id */
            id: number;
            /** Equality Columns */
            equality_columns?: string | null;
            /** Inequality Columns */
            inequality_columns?: string | null;
            /** Included Columns */
            included_columns?: string | null;
            /** User Seeks */
            user_seeks?: number | null;
            /** User Scans */
            user_scans?: number | null;
            /** Last User Seek */
            last_user_seek?: string | null;
            /** Avg Cost */
            avg_cost?: number | null;
            /** Avg Impact */
            avg_impact?: number | null;
            /** Improvement Measure */
            improvement_measure?: number | null;
            /** Suggested Ddl */
            suggested_ddl?: string | null;
            object: components["schemas"]["ObjectSummary"];
        };
        /** ObjectColumnLineage */
        ObjectColumnLineage: {
            /** Column Id */
            column_id: number;
            /** Name */
            name: string;
            /**
             * Upstream Count
             * @default 0
             */
            upstream_count: number;
            /**
             * Downstream Count
             * @default 0
             */
            downstream_count: number;
            confidences: components["schemas"]["ConfidenceCounts"];
        };
        /** ObjectDetail */
        ObjectDetail: {
            summary: components["schemas"]["ObjectSummary"];
            /** Sql Object Id */
            sql_object_id?: number | null;
            /** Ms Description */
            ms_description?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Modified At */
            modified_at?: string | null;
            parent?: components["schemas"]["ParentRef"] | null;
            /**
             * Definition Length
             * @default 0
             */
            definition_length: number;
            /**
             * Has Dynamic Sql
             * @default false
             */
            has_dynamic_sql: boolean;
            /** Is Schema Bound */
            is_schema_bound?: boolean | null;
            /** Trigger Events */
            trigger_events?: string | null;
            /** Is Instead Of Trigger */
            is_instead_of_trigger?: boolean | null;
            /** Is Disabled */
            is_disabled?: boolean | null;
            /** External Server */
            external_server?: string | null;
            /** Columns */
            columns?: components["schemas"]["Column"][];
            /** Parameters */
            parameters?: components["schemas"]["Parameter"][];
            /** Indexes */
            indexes?: components["schemas"]["Index"][];
            keys: components["schemas"]["ObjectKeys"];
            /** Triggers */
            triggers?: components["schemas"]["TriggerRef"][];
            /** Stats */
            stats?: (components["schemas"]["TableStats"] | components["schemas"]["ExecStats"]) | null;
            /** Missing Indexes */
            missing_indexes?: components["schemas"]["MissingIndex"][];
            dependencies: components["schemas"]["Dependencies"];
            lineage_counts: components["schemas"]["LineageCounts"];
            /** Lineage Issues */
            lineage_issues?: components["schemas"]["LineageIssue"][];
            annotation?: components["schemas"]["Annotation"] | null;
            /** Column Annotations */
            column_annotations?: {
                [key: string]: components["schemas"]["Annotation"];
            };
        };
        /** ObjectKeys */
        ObjectKeys: {
            primary_key?: components["schemas"]["KeyConstraint"] | null;
            /** Unique Constraints */
            unique_constraints?: components["schemas"]["KeyConstraint"][];
            /** Foreign Keys Out */
            foreign_keys_out?: components["schemas"]["ForeignKeyRef"][];
            /** Foreign Keys In */
            foreign_keys_in?: components["schemas"]["ForeignKeyRef"][];
            /** Check Constraints */
            check_constraints?: components["schemas"]["CheckConstraint"][];
        };
        /** ObjectRef */
        ObjectRef: {
            /** Id */
            id: number;
            /** Db */
            db?: string | null;
            /** Schema */
            schema?: string | null;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "table" | "view" | "procedure" | "scalar_function" | "inline_tvf" | "table_function" | "clr_function" | "trigger" | "synonym" | "sequence" | "table_type" | "temp_table" | "external";
        };
        /** ObjectSummary */
        ObjectSummary: {
            /** Id */
            id: number;
            /** Object Key */
            object_key: string;
            /** Db */
            db?: string | null;
            /** Schema */
            schema?: string | null;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "table" | "view" | "procedure" | "scalar_function" | "inline_tvf" | "table_function" | "clr_function" | "trigger" | "synonym" | "sequence" | "table_type" | "temp_table" | "external";
            /**
             * Scope
             * @enum {string}
             */
            scope: "in_scope" | "cascaded" | "external";
            /** Description */
            description?: string | null;
            /** Annotation Description */
            annotation_description?: string | null;
            /** Tags */
            tags?: string[];
            /** Row Count */
            row_count?: number | null;
            /** Total Size Kb */
            total_size_kb?: number | null;
            /** Exec Count */
            exec_count?: number | null;
            /** Modified At */
            modified_at?: string | null;
            /**
             * Lineage Status
             * @enum {string}
             */
            lineage_status: "ok" | "partial" | "failed" | "skipped" | "pending" | "n/a";
            /**
             * Has Lineage Issues
             * @default false
             */
            has_lineage_issues: boolean;
        };
        /** Parameter */
        Parameter: {
            /** Id */
            id: number;
            /** Parameter Id */
            parameter_id: number;
            /** Name */
            name: string;
            /** Type Display */
            type_display?: string | null;
            /** Is Output */
            is_output?: boolean | null;
            /** Has Default Value */
            has_default_value?: boolean | null;
            /** Default Value */
            default_value?: string | null;
            /** Is Readonly */
            is_readonly?: boolean | null;
            /** Is Table Type */
            is_table_type?: boolean | null;
            /**
             * Is Return Value
             * @default false
             */
            is_return_value: boolean;
            /** Description */
            description?: string | null;
        };
        /** ParentRef */
        ParentRef: {
            /** Id */
            id: number;
            /** Schema */
            schema?: string | null;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "table" | "view" | "procedure" | "scalar_function" | "inline_tvf" | "table_function" | "clr_function" | "trigger" | "synonym" | "sequence" | "table_type" | "temp_table" | "external";
        };
        /** ProcStatsRow */
        ProcStatsRow: {
            object: components["schemas"]["ObjectSummary"];
            /** Exec Count */
            exec_count?: number | null;
            /** Total Ms */
            total_ms?: number | null;
            /** Avg Ms */
            avg_ms?: number | null;
            /** Min Ms */
            min_ms?: number | null;
            /** Max Ms */
            max_ms?: number | null;
            /** Total Cpu Ms */
            total_cpu_ms?: number | null;
            /** Total Logical Reads */
            total_logical_reads?: number | null;
            /** Last Exec At */
            last_exec_at?: string | null;
            /** Cached Since */
            cached_since?: string | null;
        };
        /** ScanCancelled */
        ScanCancelled: {
            /** Scan Id */
            scan_id: number;
            /** Cancelled */
            cancelled: boolean;
        };
        /** ScanCounts */
        ScanCounts: {
            /**
             * Databases
             * @default 0
             */
            databases: number;
            /**
             * Schemas
             * @default 0
             */
            schemas: number;
            /**
             * Tables
             * @default 0
             */
            tables: number;
            /**
             * Views
             * @default 0
             */
            views: number;
            /**
             * Procedures
             * @default 0
             */
            procedures: number;
            /**
             * Functions
             * @default 0
             */
            functions: number;
            /**
             * Triggers
             * @default 0
             */
            triggers: number;
            /**
             * Synonyms
             * @default 0
             */
            synonyms: number;
            /**
             * Externals
             * @default 0
             */
            externals: number;
            /**
             * Cascaded
             * @default 0
             */
            cascaded: number;
            /**
             * Columns
             * @default 0
             */
            columns: number;
            /**
             * Edges Object
             * @default 0
             */
            edges_object: number;
            /**
             * Edges Column
             * @default 0
             */
            edges_column: number;
            /**
             * Lineage Issues
             * @default 0
             */
            lineage_issues: number;
            /**
             * Warnings
             * @default 0
             */
            warnings: number;
        };
        /** ScanLogEntry */
        ScanLogEntry: {
            /** Ts */
            ts: string;
            /** Level */
            level: string;
            /** Message */
            message: string;
        };
        /** ScanOptionsOut */
        ScanOptionsOut: {
            /**
             * Cascade Foreign Keys
             * @default true
             */
            cascade_foreign_keys: boolean;
            /**
             * Include Triggers Of Cascaded Tables
             * @default true
             */
            include_triggers_of_cascaded_tables: boolean;
            /**
             * Collect Stats
             * @default true
             */
            collect_stats: boolean;
            /**
             * Parse Lineage
             * @default true
             */
            parse_lineage: boolean;
        };
        /** ScanOverview */
        ScanOverview: {
            /** Databases */
            databases: components["schemas"]["DatabaseOverview"][];
            counts: components["schemas"]["ScanCounts"];
            /** Lineage Coverage */
            lineage_coverage?: number | null;
            warnings_summary: components["schemas"]["WarningsSummary"];
            /** Warnings */
            warnings?: components["schemas"]["ScanWarningOut"][];
        };
        /** ScanProgressInfo */
        ScanProgressInfo: {
            /** Phase */
            phase?: ("connect" | "enumerate" | "cascade" | "extract" | "stats" | "lineage" | "finalize") | null;
            /**
             * Phase Index
             * @default 0
             */
            phase_index: number;
            /**
             * Phase Count
             * @default 7
             */
            phase_count: number;
            /**
             * Current
             * @default 0
             */
            current: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Message
             * @default
             */
            message: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ScanStartRequest */
        ScanStartRequest: {
            /** Collect Stats */
            collect_stats?: boolean | null;
            /** Parse Lineage */
            parse_lineage?: boolean | null;
            /** Cascade Foreign Keys */
            cascade_foreign_keys?: boolean | null;
            /** Include Triggers Of Cascaded Tables */
            include_triggers_of_cascaded_tables?: boolean | null;
        };
        /** ScanStarted */
        ScanStarted: {
            /** Scan Id */
            scan_id: number;
        };
        /** ScanStatus */
        ScanStatus: {
            /** Id */
            id: number;
            /** Connection */
            connection: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "cancelled";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            options?: components["schemas"]["ScanOptionsOut"] | null;
            counts?: components["schemas"]["ScanCounts"] | null;
            /** Error */
            error?: string | null;
            /** Server Name */
            server_name?: string | null;
            /** Server Version */
            server_version?: string | null;
            /** Server Edition */
            server_edition?: string | null;
            /** Auth Scheme */
            auth_scheme?: string | null;
            /** Driver */
            driver?: ("pyodbc" | "pymssql") | null;
            progress: components["schemas"]["ScanProgressInfo"];
            /** Warnings */
            warnings?: components["schemas"]["ScanWarningOut"][];
            /** Log */
            log?: components["schemas"]["ScanLogEntry"][];
        };
        /** ScanSummary */
        ScanSummary: {
            /** Id */
            id: number;
            /** Connection */
            connection: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "cancelled";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            options?: components["schemas"]["ScanOptionsOut"] | null;
            counts?: components["schemas"]["ScanCounts"] | null;
            /** Error */
            error?: string | null;
            /** Server Name */
            server_name?: string | null;
            /** Server Version */
            server_version?: string | null;
            /** Server Edition */
            server_edition?: string | null;
            /** Auth Scheme */
            auth_scheme?: string | null;
            /** Driver */
            driver?: ("pyodbc" | "pymssql") | null;
        };
        /** ScanWarningOut */
        ScanWarningOut: {
            /**
             * Phase
             * @enum {string}
             */
            phase: "connect" | "enumerate" | "cascade" | "extract" | "stats" | "lineage" | "finalize";
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Database */
            database?: string | null;
        };
        /** SchemaOverview */
        SchemaOverview: {
            /** Name */
            name: string;
            /** Is Selected */
            is_selected: boolean;
            /** Counts By Kind */
            counts_by_kind: {
                [key: string]: number;
            };
        };
        /** SearchColumnHit */
        SearchColumnHit: {
            object: components["schemas"]["ObjectSummary"];
            /** Column */
            column: string;
            /** Data Type */
            data_type?: string | null;
        };
        /** SearchMatch */
        SearchMatch: {
            /** Field */
            field: string;
            /** Snippet */
            snippet?: string | null;
        };
        /** SearchObjectHit */
        SearchObjectHit: {
            /** Id */
            id: number;
            /** Object Key */
            object_key: string;
            /** Db */
            db?: string | null;
            /** Schema */
            schema?: string | null;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "table" | "view" | "procedure" | "scalar_function" | "inline_tvf" | "table_function" | "clr_function" | "trigger" | "synonym" | "sequence" | "table_type" | "temp_table" | "external";
            /**
             * Scope
             * @enum {string}
             */
            scope: "in_scope" | "cascaded" | "external";
            /** Description */
            description?: string | null;
            /** Annotation Description */
            annotation_description?: string | null;
            /** Tags */
            tags?: string[];
            /** Row Count */
            row_count?: number | null;
            /** Total Size Kb */
            total_size_kb?: number | null;
            /** Exec Count */
            exec_count?: number | null;
            /** Modified At */
            modified_at?: string | null;
            /**
             * Lineage Status
             * @enum {string}
             */
            lineage_status: "ok" | "partial" | "failed" | "skipped" | "pending" | "n/a";
            /**
             * Has Lineage Issues
             * @default false
             */
            has_lineage_issues: boolean;
            match: components["schemas"]["SearchMatch"];
        };
        /** SearchResult */
        SearchResult: {
            /** Objects */
            objects?: components["schemas"]["SearchObjectHit"][];
            /** Columns */
            columns?: components["schemas"]["SearchColumnHit"][];
        };
        /** TableStats */
        TableStats: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "table";
            /** Row Count */
            row_count?: number | null;
            /** Data Kb */
            data_kb?: number | null;
            /** Index Kb */
            index_kb?: number | null;
            /** Reserved Kb */
            reserved_kb?: number | null;
            /** Partition Count */
            partition_count?: number | null;
            /** Is Heap */
            is_heap?: boolean | null;
            /** Compression */
            compression?: string | null;
            /** Stats As Of */
            stats_as_of?: string | null;
        };
        /** TableStatsRow */
        TableStatsRow: {
            object: components["schemas"]["ObjectSummary"];
            /** Row Count */
            row_count?: number | null;
            /** Data Kb */
            data_kb?: number | null;
            /** Index Kb */
            index_kb?: number | null;
            /** Reserved Kb */
            reserved_kb?: number | null;
            /** Partition Count */
            partition_count?: number | null;
            /** Is Heap */
            is_heap?: boolean | null;
            /** Compression */
            compression?: string | null;
        };
        /** TagInfo */
        TagInfo: {
            /** Tag */
            tag: string;
            /** Color */
            color?: string | null;
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /** TriggerRef */
        TriggerRef: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Events */
            events?: string | null;
            /** Is Instead Of */
            is_instead_of?: boolean | null;
            /** Is Disabled */
            is_disabled?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WarningsSummary */
        WarningsSummary: {
            /**
             * Lineage Issues
             * @default 0
             */
            lineage_issues: number;
            /**
             * Unused Indexes
             * @default 0
             */
            unused_indexes: number;
            /**
             * Missing Index Suggestions
             * @default 0
             */
            missing_index_suggestions: number;
            /**
             * External Refs
             * @default 0
             */
            external_refs: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_connections_api_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_ConnectionInfo_"];
                };
            };
        };
    };
    test_connection_api_connections__name__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scans_api_connections__name__scans_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_ScanSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_scan_api_connections__name__scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ScanStartRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scan_api_scans__scan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_scan_api_scans__scan_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanCancelled"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_summary_api_scans__scan_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_objects_api_scans__scan_id__objects_get: {
        parameters: {
            query?: {
                db?: string | null;
                schema?: string | null;
                /** @description comma separated object kinds */
                kind?: string | null;
                /** @description comma separated: in_scope,cascaded,external */
                scope?: string | null;
                q?: string | null;
                tag?: string | null;
                has_issues?: boolean | null;
                sort?: "name" | "kind" | "schema" | "rows" | "size" | "execs" | "modified";
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_ObjectSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_object_api_scans__scan_id__objects_lookup_get: {
        parameters: {
            query: {
                db: string;
                schema: string;
                name: string;
            };
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_api_scans__scan_id__objects__object_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: number;
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_definition_api_scans__scan_id__objects__object_id__definition_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: number;
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Definition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_scans__scan_id__search_get: {
        parameters: {
            query: {
                q: string;
                /** @description comma separated: object,column,definition */
                kinds?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    object_graph_api_scans__scan_id__lineage_objects_get: {
        parameters: {
            query: {
                /** @description object id */
                focus: number;
                direction?: "up" | "down" | "both";
                depth?: number;
                /** @description comma separated object kinds to include */
                kinds?: string | null;
                /** @description comma separated schema names to include */
                schemas?: string | null;
                /** @description comma separated edge kinds to follow */
                edge_kinds?: string | null;
                include_cascaded?: boolean;
                include_external?: boolean;
                max_nodes?: number;
            };
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    column_graph_api_scans__scan_id__lineage_columns_get: {
        parameters: {
            query: {
                /** @description object id */
                focus: number;
                /** @description seed column; omit for all lineage-bearing */
                column?: string | null;
                direction?: "up" | "down" | "both";
                depth?: number;
                min_confidence?: "unresolved" | "inferred" | "exact";
                collapse_temp?: boolean;
                max_nodes?: number;
            };
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnLineageGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    object_columns_api_scans__scan_id__lineage_objects__object_id__columns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: number;
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectColumnLineage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lineage_summary_api_scans__scan_id__lineage_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lineage_issues_api_scans__scan_id__lineage_issues_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_LineageIssueItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tables_api_scans__scan_id__stats_tables_get: {
        parameters: {
            query?: {
                db?: string | null;
                schema?: string | null;
                sort?: "rows" | "data_kb" | "index_kb" | "reserved_kb" | "size" | "partitions" | "name";
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_TableStatsRow_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    indexes_api_scans__scan_id__stats_indexes_get: {
        parameters: {
            query?: {
                db?: string | null;
                schema?: string | null;
                unused?: boolean;
                sort?: "updates" | "seeks" | "scans" | "lookups" | "name" | "table";
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_IndexStatsRow_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    procs_api_scans__scan_id__stats_procs_get: {
        parameters: {
            query?: {
                db?: string | null;
                schema?: string | null;
                sort?: "exec_count" | "total_ms" | "avg_ms" | "max_ms" | "cpu" | "reads" | "last_exec" | "name";
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_ProcStatsRow_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    missing_indexes_api_scans__scan_id__stats_missing_indexes_get: {
        parameters: {
            query?: {
                db?: string | null;
                schema?: string | null;
                sort?: "improvement" | "seeks" | "impact" | "cost" | "name";
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_MissingIndexRow_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_annotations_api_annotations_get: {
        parameters: {
            query?: {
                connection?: string | null;
                tag?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_Annotation_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_annotation_api_annotations_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnotationUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Annotation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_annotation_api_annotations_delete: {
        parameters: {
            query: {
                connection: string;
                db: string;
                schema: string;
                name: string;
                column?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: {
                connection?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
}
