/**
 * Named aliases over the generated OpenAPI schema (`schema.d.ts`, regenerated by
 * `npm run api:types`). Keep this file free of hand-written response shapes: every type that
 * describes an API payload must derive from `components['schemas']` or `paths` so the UI
 * cannot drift from the backend contract.
 */
import type { components, paths } from './schema'

type S = components['schemas']
type Query<P extends keyof paths> = paths[P] extends { get: { parameters: { query?: infer Q } } } ? NonNullable<Q> : never

// ---------------------------------------------------------------------------
// Enums (string-literal unions straight from the contract)
// ---------------------------------------------------------------------------

export type ObjectKind = S['ObjectSummary']['kind']
export type ObjectScope = S['ObjectSummary']['scope']
export type LineageStatus = S['ObjectSummary']['lineage_status']
export type ScanStatus = S['ScanSummary']['status']
export type ScanPhase = S['ScanWarningOut']['phase']
export type EdgeKind = S['LineageEdge']['kind']
export type Resolution = S['LineageEdge']['resolution']
export type Confidence = S['ColumnLineageEdge']['confidence']
export type Transform = S['ColumnLineageEdge']['transform']
export type ColumnKind = S['Column']['column_kind']
export type LineageIssueKind = S['LineageIssue']['kind']
export type LineageDirection = NonNullable<Query<'/api/scans/{scan_id}/lineage/objects'>['direction']>
export type SortOrder = NonNullable<Query<'/api/scans/{scan_id}/objects'>['order']>
export type ObjectSort = NonNullable<Query<'/api/scans/{scan_id}/objects'>['sort']>
export type TableStatsSort = NonNullable<Query<'/api/scans/{scan_id}/stats/tables'>['sort']>
export type IndexStatsSort = NonNullable<Query<'/api/scans/{scan_id}/stats/indexes'>['sort']>
export type ProcStatsSort = NonNullable<Query<'/api/scans/{scan_id}/stats/procs'>['sort']>
export type MissingIndexSort = NonNullable<Query<'/api/scans/{scan_id}/stats/missing-indexes'>['sort']>

// ---------------------------------------------------------------------------
// Envelopes / errors
// ---------------------------------------------------------------------------

export interface Paged<T> {
  items: T[]
  total: number
  limit: number
  offset: number
}

export type ValidationError = S['ValidationError']
export interface ApiErrorDetail {
  detail: string | ValidationError[]
  /** Added by the client middleware (see `api/client.ts`). */
  status?: number
}

// ---------------------------------------------------------------------------
// Connections / config / health
// ---------------------------------------------------------------------------

export type ConnectionDatabase = S['ConnectionDatabase']
export type ConnectionInfo = S['ConnectionInfo']
export type ConnectionList = S['ListEnvelope_ConnectionInfo_']
export type ConnectionTestDatabase = S['ConnectionTestDatabase']
export type ConnectionTestResult = S['ConnectionTestResult']
export type AppConfig = S['ConfigOut']
export type Health = S['Health']

// ---------------------------------------------------------------------------
// Scans
// ---------------------------------------------------------------------------

export type ScanCounts = S['ScanCounts']
export type ScanOptions = S['ScanOptionsOut']
export type ScanSummary = S['ScanSummary']
export type ScanProgress = S['ScanProgressInfo']
export type ScanWarning = S['ScanWarningOut']
export type ScanLogEntry = S['ScanLogEntry']
/** `GET /api/scans/{scan_id}` — summary + live progress + warnings. */
export type ScanDetail = S['ScanStatus']
export type StartScanRequest = S['ScanStartRequest']
export type StartScanResponse = S['ScanStarted']
export type ScanCancelled = S['ScanCancelled']
export type SchemaSummary = S['SchemaOverview']
export type DatabaseSummary = S['DatabaseOverview']
export type SnapshotSummary = S['ScanOverview']
export type WarningsSummary = S['WarningsSummary']

// ---------------------------------------------------------------------------
// Catalog
// ---------------------------------------------------------------------------

export type ObjectSummary = S['ObjectSummary']
export type ObjectRefLite = S['ObjectRef']
export type ParentRef = S['ParentRef']
export type SearchMatch = S['SearchMatch']
export type SearchObjectHit = S['SearchObjectHit']
export type SearchColumnHit = S['SearchColumnHit']
export type SearchResult = S['SearchResult']
export type ColumnLineageCounts = S['ColumnLineageCounts']
export type Column = S['Column']
export type FkTarget = S['FkTarget']
export type Parameter = S['Parameter']
export type IndexUsage = S['IndexUsage']
export type IndexKeyColumn = S['IndexKeyColumn']
export type Index = S['Index']
export type KeyConstraint = S['KeyConstraint']
export type ForeignKey = S['ForeignKeyRef']
export type ForeignKeyColumnPair = S['ForeignKeyColumnPair']
export type CheckConstraint = S['CheckConstraint']
export type ObjectKeys = S['ObjectKeys']
export type TriggerRef = S['TriggerRef']
export type TableStats = S['TableStats']
export type ExecStats = S['ExecStats']
export type ObjectStats = TableStats | ExecStats
export type MissingIndex = S['MissingIndex']
export type DepRef = S['DepRef']
export type Dependencies = S['Dependencies']
export type LineageIssue = S['LineageIssue']
export type Annotation = S['Annotation']
export type ObjectDetail = S['ObjectDetail']
export type ObjectDefinition = S['Definition']

// ---------------------------------------------------------------------------
// Lineage
// ---------------------------------------------------------------------------

export type LineageMore = S['LineageMore']
export type LineageNode = S['LineageNode']
export type LineageEdge = S['LineageEdge']
export type LineageGraph = S['LineageGraph']
export type ColumnLineageNodeColumn = S['ColumnLineageNodeColumn']
export type ColumnLineageNode = S['ColumnLineageNode']
export type ColumnLineageEdge = S['ColumnLineageEdge']
export type ColumnLineageGraph = S['ColumnLineageGraph']
export type ObjectColumnLineage = S['ObjectColumnLineage']
export type ConfidenceCounts = S['ConfidenceCounts']
export type LineageHub = S['LineageHub']
export type LineageSummary = S['LineageSummary']
export type LineageIssueRow = S['LineageIssueItem']

// ---------------------------------------------------------------------------
// Stats grids
// ---------------------------------------------------------------------------

export type TableStatsRow = S['TableStatsRow']
export type IndexStatsRow = S['IndexStatsRow']
export type ProcStatsRow = S['ProcStatsRow']
export type MissingIndexRow = S['MissingIndexRow']

// ---------------------------------------------------------------------------
// Annotations & tags
// ---------------------------------------------------------------------------

export type AnnotationUpsert = S['AnnotationUpsert']
export type AnnotationKey = Query<'/api/annotations'> extends never ? never : paths['/api/annotations']['delete']['parameters']['query']
export type Tag = S['TagInfo']
